version: 0.2

phases:
  install:
    commands:
      - npm install -g yarn
      - yarn
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - aws s3 sync dist s3://ci-cd-sandbox --delete
